export const metadata = {
  title: "Sevdem Maya - Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return <main>{children}</main>;
}
