import "./globals.css";
import { Source_Sans_3 } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import ToastContainerWrapper from "@/components/ui/ToastContainerWrapper";

export const metadata = {
  title: "Template",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    { rel: "icon", url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    { rel: "apple-touch-icon", url: "/apple-touch-icon.png", sizes: "180x180" },
  ],
  manifest: "/site.webmanifest",
};

const lato = Source_Sans_3({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" className={lato.className}>
        <body>
          {children}
          <ToastContainerWrapper />
        </body>
      </html>
    </ClerkProvider>
  );
}
