export const metadata = {
  title: "Sevdem Maya - Ekşi Maya Ekmek",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  return <main>{children}</main>;
}
